version: "3.8"
services:
  api:
    build:
      context: ./docker
      dockerfile: api/Dockerfile
    image: mainsail-stack-api/1
    volumes:
      - ./docker/config:/home/node/klipper_config
      - ./docker/logs:/home/node/klipper_logs
      - ./docker/gcode:/home/node/gcode
      - ./docker/config/moonraker:/home/node/.moonraker_database
    container_name: mainsail-stack-api
    ports:
      - "7125:7125"
    networks:
      - dev_net
  npm:
    build:
      context: .
      dockerfile: docker/Dockerfile
    image: mainsail-stack-npm/1
    env_file:
      - .env
    volumes:
      - ./src/:/home/node/mainsail/src
      - ./public/:/home/node/mainsail/public
      - ./vie-config.ts:/vite.config.ts
    container_name: mainsail-stack-npm
    ports:
      - "8080:8080"
    depends_on:
      - api
    networks:
      - dev_net
networks:
  dev_net:
    driver: bridge
