version: '3.8'
services:
  api:
    build:
      context: ./docker
      dockerfile: api/Dockerfile
    image: mainsail-stack-api/1
    volumes:
      - ./docker/config:/home/node/klipper_config
      - ./docker/logs:/home/node/klipper_logs
      - ./docker/gcode:/home/node/gcode
      - ./docker/config/moonraker:/home/node/.moonraker_database
    container_name: mainsail-stack-api
    ports:
      - '7125:7125'
    networks:
      - dev_net
  npm:
    build:
      context: .
      dockerfile: docker/Dockerfile
    image: mainsail-stack-npm/1
    volumes:
      # Do not bind '.' as volume.  As we want the node modules being installed in the container
      - ./src/:/home/node/mainsail/src
      - ./public/:/home/node/mainsail/public
      - ./vite.config.ts:/home/node/mainsail/vite.config.ts
      - ./index.html:/home/node/mainsail/index.html
    container_name: mainsail-stack-npm
    ports:
      - '8080:8080'
    depends_on:
      - api
    networks:
      - dev_net
networks:
  dev_net:
    driver: bridge
