name: 'â‘‡ size-report'

on: workflow_call

jobs:
  check_locale:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
          ref: ${{ github.event.pull_request.head.sha }}
      - uses: actions/setup-node@v3
        with:
          node-version: '16'
          cache: 'npm'
      - uses: actions/cache@v3
        id: cache
        with:
          path: node_modules/
          key: ${{ runner.os }}-${{ hashFiles('package-lock.json') }}

      - name: Check package.json was changed
        id: changed-file-package-json
        uses: tj-actions/changed-files@v23
        with:
          sha: ${{ github.event.pull_request.head.sha }}
          files: 'package-lock.json'

      - uses: preactjs/compressed-size-action@v2
        if: steps.changed-file-package-json.outputs.any_changed == 'true'
        with:
          strip-hash: "\\b\\w{8}\\."
          pattern: './dist/**/*.{js,css,html,json,woff2,svg,png}'
          exclude: '{./dist/manifest.json,./dist/build.zip,**/*.map,**/node_modules/**}'
