name: Build Size Report
on:
  pull_request_target:
    types: [labeled]
jobs:
  check:
    runs-on: ubuntu-latest
    if: contains(github.event.pull_request.labels.*.name, 'analyze')
    timeout-minutes: 30
    steps:
      - uses: actions/checkout@v2
        with:
          ref: ${{ github.event.pull_request.head.sha }}
      - uses: preactjs/compressed-size-action@v2
        with:
          strip-hash: "\\b\\w{8}\\."
          pattern: './dist/**/*.{js,css,html,json}'
          exclude: '{./dist/manifest.json,./dist/build.zip,**/*.map,**/node_modules/**}'
      - uses: actions-ecosystem/action-remove-labels@v1
        with:
          labels: analyze # analyze complete, remote the label afterwards
