name: Check Translations
on:
  pull_request:
    types: [synchronize, opened]
    paths:
      - 'src/locales/**'

jobs:
  check_translations:
    runs-on: ubuntu-latest
    steps:
      - name: Install jq
        run: sudo apt install -y jq

      - name: Fetch repo
        uses: actions/checkout@v5

      - name: Install node
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install dependencies
        run: npm ci

      - name: Get changed files
        id: changed-files
        uses: tj-actions/changed-files@v46
        with:
          files: 'src/locales/*.json'

      - name: Run i18n-extract on changed locale files
        id: i18n-extract
        run: |
          mkdir ./i18n-extract
          ls -l ./src/locales/*.json
          for file in ${{ steps.changed-files.outputs.all_changed_files }}; do
            cat "$file" | jq empty || { echo "Invalid JSON in $file"; exit 1; }
            locale=$(basename "$file" .json)
            languageFiles="./src/locales/${locale}.json"
            outputDir="./i18n-extract/${locale}"

            echo "Extracting i18n data for locale: $locale"
            echo "Language files: $languageFiles"
            echo "Output directory: $outputDir"

            npx vue-i18n-extract --vueFiles './src/**/{*.?(js|ts|vue),.i18nignore}' --languageFiles '${languageFiles}' --output '${outputDir}'
            MISSING=$(cat i18n-extract/${locale} | jq '.missingKeys | length')
            UNUSED=$(cat i18n-extract/${locale} | jq '.unusedKeys | length')
            echo "$file=|${file##*/}|${MISSING}|${UNUSED}|" >> $GITHUB_OUTPUT
          done

      - name: Comment PR
        uses: thollander/actions-comment-pull-request@v3
        with:
          message: |
            Language file analysis report:
            |File|Missing Keys|Unused Keys|
            |:---|---:|---:|
            ${{join(steps.i18n-extract.outputs.*, '
            ')}}
