name: PR Bundle Size

on:
  pull_request_target:
    types: [opened, synchronize]
    paths:
      - 'package.json'
      - 'package-lock.json'

jobs:
  bundle-size:
    name: Analyze bundle size
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write
    steps:
      - uses: preactjs/compressed-size-action@v2
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          strip-hash: "\\b\\w{8}\\."
          pattern: './dist/**/*.{js,css,html,json,woff2,svg,png}'
          exclude: '{./dist/manifest.json,./dist/build.zip,**/*.map,**/node_modules/**}'
