name: PR Checks

on:
  pull_request:
    types: [synchronize, opened, reopened]

jobs:
  code-style:
    name: Code style check
    runs-on: ubuntu-latest
    permissions:
      checks: write
    steps:
      - name: Checkout
        uses: actions/checkout@v6

      - name: Install node
        uses: actions/setup-node@v6
        with:
          node-version: 20

      - name: Install dependencies
        run: npm ci

      - name: Run linters
        uses: wearerequired/lint-action@v2
        with:
          eslint: true
          prettier: true

  check-translations:
    name: Check translations
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v6

      - name: Get changed files
        id: changed-files
        uses: tj-actions/changed-files@24d32ffd492484c1d75e0c0b894501ddb9d30d62 # v47
        with:
          files: 'src/locales/*.json'

      - name: Install jq
        if: steps.changed-files.outputs.any_changed == 'true'
        run: sudo apt install -y jq

      - name: Install node
        if: steps.changed-files.outputs.any_changed == 'true'
        uses: actions/setup-node@v6
        with:
          node-version: 20

      - name: Install dependencies
        if: steps.changed-files.outputs.any_changed == 'true'
        run: npm ci

      - name: Run i18n-extract
        if: steps.changed-files.outputs.any_changed == 'true'
        id: i18n-extract
        env:
          CHANGED_FILES: ${{ steps.changed-files.outputs.all_changed_files }}
        run: |
          mkdir ./i18n-extract

          for file in ${CHANGED_FILES}; do
            locale=$(basename "$file" .json)
            languageFiles="./src/locales/${locale}.json"
            outputFile="./i18n-extract/${locale}.json"

            echo "::group::Extracting i18n data for locale: ${locale}"

            npx vue-i18n-extract \
              --vueFiles './src/**/{*.?(js|ts|vue),.i18nignore}' \
              --languageFiles "${languageFiles}" \
              --output "${outputFile}"

            echo "::endgroup::"
          done

      - name: Create translation report
        if: steps.changed-files.outputs.any_changed == 'true'
        id: report
        env:
          CHANGED_FILES: ${{ steps.changed-files.outputs.all_changed_files }}
        run: |
          echo "## Language file analysis report" > translation-report.md
          echo "" >> translation-report.md
          echo "|File|Missing Keys|Unused Keys|" >> translation-report.md
          echo "|:---|---:|---:|" >> translation-report.md

          for file in ${CHANGED_FILES}; do
            locale=$(basename "$file" .json)
            outputFile="./i18n-extract/${locale}.json"
            
            MISSING=$(cat "${outputFile}" | jq '.missingKeys | length')
            UNUSED=$(cat "${outputFile}" | jq '.unusedKeys | length')
            
            echo "|${file##*/}|${MISSING}|${UNUSED}|" >> translation-report.md
          done

      - name: Upload translation report
        if: steps.changed-files.outputs.any_changed == 'true'
        uses: actions/upload-artifact@v5
        with:
          name: translation-report
          path: translation-report.md
